// MongoDB Contact Schema Reference
// Collection: contacts

/*
{
  _id:       ObjectId (auto-generated by MongoDB),
  name:      String   (required),
  phone:     String   (required),
  email:     String   (required, lowercase),
  createdAt: Date     (auto by timestamps),
  updatedAt: Date     (auto by timestamps)
}
*/
